/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists conversations */
        get: operations["list_conversations"];
        put?: never;
        /** Creates a new conversation */
        post: operations["create_new_conversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conv_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancels and deletes a conversation */
        delete: operations["cancel_and_delete_conversation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conv_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resumes a conversation */
        get: operations["get_messages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conv_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Streams back assistant completion chunks */
        post: operations["chat_stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Computes key performance metrics */
        get: operations["get_telemetry_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves chronological telemetry points */
        get: operations["get_telemetry_timeseries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists the latest raw telemetry logs */
        get: operations["get_recent_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ConversationCreate: {
            title?: string | null;
        };
        ChatRequest: {
            prompt: string;
            provider: string;
            model: string;
        };
        ConversationResponse: {
            id: string;
            title: string;
            created_at: string;
            updated_at: string;
        };
        MessageResponse: {
            id: string;
            role: string;
            content: string;
            created_at: string;
        };
        ConversationDeleteResponse: {
            status: string;
            message: string;
        };
        ProviderStats: {
            calls: number;
            errors: number;
            success_rate: number;
        };
        ModelStats: {
            calls: number;
            avg_latency_ms: number;
        };
        MetricsResponse: {
            total_calls: number;
            success_rate: number;
            avg_latency_ms: number;
            total_tokens: number;
            avg_throughput_tps: number;
            error_rate: number;
            provider_breakdown: {
                [key: string]: components["schemas"]["ProviderStats"];
            };
            model_breakdown: {
                [key: string]: components["schemas"]["ModelStats"];
            };
        };
        TimeseriesPointResponse: {
            id: string;
            timestamp: string;
            latency_ms: number;
            tokens_total: number;
            tokens_prompt: number;
            tokens_completion: number;
            throughput_tps: number;
            status: string;
            model: string;
            provider: string;
        };
        TelemetryLogResponse: {
            id: string;
            conversation_id?: string | null;
            message_id?: string | null;
            provider: string;
            model: string;
            status: string;
            latency_ms: number;
            tokens_prompt: number;
            tokens_completion: number;
            tokens_total: number;
            error_message?: string | null;
            pii_redacted: boolean;
            metadata: Record<string, never>;
            timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_conversations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"][];
                };
            };
        };
    };
    create_new_conversation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
        };
    };
    cancel_and_delete_conversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDeleteResponse"];
                };
            };
        };
    };
    get_messages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"][];
                };
            };
        };
    };
    chat_stream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conv_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response (Event Source Stream) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    get_telemetry_metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
        };
    };
    get_telemetry_timeseries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeseriesPointResponse"][];
                };
            };
        };
    };
    get_recent_logs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryLogResponse"][];
                };
            };
        };
    };
}
